{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"Target": {
		"EntitySet": "ProductTexts",
		"Service": "/DemoSampleApp/Services/sample.service",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"Id": "#Control:Id/#Value",
		"Language": "#Control:Language/#Value",
		"LongDescription": "#Control:LongDescription/#Value",
		"Name": "#Control:Name/#Value",
		"ProductId": "#Control:ProductId/#Value",
		"ShortDescription": "#Control:ShortDescription/#Value"
	},
	"UpdateLinks": [],
	"ActionResult": {
		"_Name": "update"
	},
	"OnSuccess": "/DemoSampleApp/Actions/UpdateEntitySuccessMessage.action",
	"OnFailure": "/DemoSampleApp/Actions/UpdateEntityFailureMessage.action"
}