{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"Target": {
		"EntitySet": "PurchaseOrderHeaders",
		"Service": "/DemoSampleApp/Services/sample.service",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"CurrencyCode": "#Control:CurrencyCode/#Value",
		"GrossAmount": "#Control:GrossAmount/#Value",
		"NetAmount": "#Control:NetAmount/#Value",
		"PurchaseOrderId": "#Control:PurchaseOrderId/#Value",
		"SupplierId": "#Control:SupplierId/#Value",
		"TaxAmount": "#Control:TaxAmount/#Value"
	},
	"UpdateLinks": [],
	"ActionResult": {
		"_Name": "update"
	},
	"OnSuccess": "/DemoSampleApp/Actions/UpdateEntitySuccessMessage.action",
	"OnFailure": "/DemoSampleApp/Actions/UpdateEntityFailureMessage.action"
}